AA_count: 21
alignment: /scratch/user/s4646506/gcn4/encoded_weighted/gcn4_ancestors_extants_no_dupes_clustered_r3_extant_0.025_encoded_weighted.pkl
architecture: SeqVAE_softmax
batch_size: 256
dms_file: /scratch/user/s4646506/gcn4/dms_data/GCN4_YEAST_Staller_2018.pkl
dms_id: GCN4_YEAST_Staller_2018
dms_metadata: /scratch/user/s4646506/evoVAE/data/DMS_substitutions.csv
dropout: 0.01
epochs: 800
extant_aln: /scratch/user/s4646506/gcn4/encoded_weighted/gcn4_extants_encoded_weighted.pkl
hidden_dims:
- 256
- 128
- 64
info: ./rep_3_train_gcn4_ancestors_extants_no_dupes_clustered_r3_extant_0025_encoded_weighted_dms_GCN4_YEAST_Staller_2018_covar_gcn4_extants_encoded_weighted/
latent_dims: 3
latent_samples: 50
learning_rate: 0.01
max_mutation: 4
max_norm: -1
num_processes: 8
patience: 10
project: gcn4_clustering
replicate: 3
seq_theta: 0.2
test_split: 0.2
weight_decay: 0
