AA_count: 21
alignment: /scratch/user/s4646506/gcn4/encoded_weighted/gcn4_ancestors_extants_no_dupes.pkl
architecture: SeqVAE_softmax
batch_size: 128
replicate_csv: /scratch/user/s4646506/gcn4/gcn4_0.02_replicates.csv
dms_file: /scratch/user/s4646506/gcn4/dms_data/GCN4_YEAST_Staller_2018.pkl
dms_id: GCN4_YEAST_Staller_2018
dms_metadata: /scratch/user/s4646506/evoVAE/data/DMS_substitutions.csv
dropout: 0.025
epochs: 150
extant_aln: /scratch/user/s4646506/gcn4/encoded_weighted/gcn4_extants_no_dupes.pkl
hidden_dims:
- 256
- 128
- 64
info: ./gcn4_0.02_extants
latent_dims: 3
latent_samples: 50
learning_rate: 0.01
max_mutation: 4
max_norm: -1
num_processes: 8
patience: 3
project: gcn4_clustering
replicate: 1
seq_theta: 0.2
test_split: 0.2
weight_decay: 0
