# Dataset info
alignment: /scratch/user/s4646506/gb1/encoded_weighted/gb1_extants_encoded_weighted_no_dupes.pkl
info: lr_0.0001_b_64_wdecay_0.0001
project: GB1_tuning
seq_theta: 0.2  # reweighting
AA_count: 21  # standard AA + gap
test_split: 0.2
max_mutation: 4 # how many mutations the model will test up to
# ADAM
learning_rate: 0.0001 # ADAM
weight_decay: 0.0001 # ADAM
# Hidden units
momentum: None
dropout: None
# Training loop
epochs: 300
batch_size: 64
patience: 5 
max_norm: 5  # gradient clipping
# Model info - default settings
architecture: SeqVAE_reg_softmax
latent_dims: 3
hidden_dims: [256, 128, 64]
# DMS data
dms_file: /scratch/user/s4646506/gb1/dms_data/SPG1_STRSG_Wu_2016.pkl
dms_metadata: /scratch/user/s4646506/evoVAE/data/DMS_substitutions.csv
dms_id: SPG1_STRSG_Wu_2016

extant_config: /scratch/user/s4646506/gb1/encoded_weighted/gb1_extants_encoded_weighted_no_dupes.pkl
extant_aln: /scratch/user/s4646506/gb1/encoded_weighted/gb1_extants_encoded_weighted_no_dupes.pkl
