# Dataset info
alignment: ../data/gb1/gb1_ancestors_extants_encoded_weighted_no_dupes.pkl
info: gb1_ancestors_extants_no_dupes
project: GB1_SeqVAE
seq_theta: 0.2  # reweighting
AA_count: 21  # standard AA + gap
test_split: 0.2
max_mutation: 4 # how many mutations the model will test up to
# ADAM
learning_rate: 0.001 # ADAM
weight_decay: 0.0001 # ADAM
# Hidden units
momentum: None
dropout: None
# Training loop
epochs: 400
batch_size: 128
patience: 3
max_norm: 5 # gradient clipping
# Model info - default settings
architecture: SeqVAE_reg_softmax
latent_dims: 2
hidden_dims: [256, 128, 64]
# DMS data
dms_file: ../data/gb1/SPG1_STRSG_Wu_2016.pkl
dms_metadata: ../data/DMS_substitutions.csv
dms_id: SPG1_STRSG_Wu_2016

