AA_count: 21
alignment: /scratch/user/s4646506/gb1/encoded_weighted/gb1_ancestors_extants_no_dupes.pkl
architecture: SeqVAEv2
batch_size: 128
dms_file: /scratch/user/s4646506/gb1/dms_data/SPG1_STRSG_Wu_2016.pkl
dms_id: SPG1_STRSG_Wu_2016
dms_metadata: /scratch/user/s4646506/evoVAE/data/DMS_substitutions.csv
dropout: 0.025
epochs: 200
extant_aln: /scratch/user/s4646506/gb1/encoded_weighted/gb1_extants_no_dupes.pkl
hidden_dims:
- 150
- 150
info: ./gb1_0.1_extants
latent_dims: 3
learning_rate: 0.01
max_mutation: 4
max_norm: -1
num_processes: 8
patience: 3
project: null
replicate_csv: /scratch/user/s4646506/gb1/gb1_0.1_replicates.csv
seq_theta: 0.2
test_split: 0.2
weight_decay: 0
