AA_count: 21
alignment: /scratch/user/s4646506/gfp/encoded_weighted/gfp_ancestors_extants_no_syn_no_dupes.pkl
architecture: SeqVAEv2
batch_size: 128
dms_file: /scratch/user/s4646506/gfp/dms_data/GFP_AEQVI_Sarkisyan_2016_dms_encoded.pkl
dms_id: GFP_AEQVI_Sarkisyan_2016
dms_metadata: /scratch/user/s4646506/evoVAE/data/DMS_substitutions.csv
dropout: 0.025
epochs: 200
extant_aln: /scratch/user/s4646506/gfp/encoded_weighted/gfp_extants_no_syn_no_dupes.pkl
hidden_dims:
- 150
- 150
info: ./gfp_ae
latent_dims: 3
learning_rate: 0.01
max_mutation: 4
max_norm: -1
num_processes: 8
patience: 3
project: null
replicate_csv: null
seq_theta: 0.2
test_split: 0.2
weight_decay: 0
